//@version=6
indicator("Super Trend Multi Time Frame Short", overlay=true)

atrPeriod = input.int(10,    "ATR Length", minval = 1)
factor    = input.float(3.0, "Factor",     minval = 0.01, step = 0.01)

higherTimeFrame = switch timeframe.period
    "1"  => "3"
    "2"  => "5"
    "3"  => "5"
    "5"  => "15"
    => "60"


[l_supertrend, l_direction] = ta.supertrend(factor, atrPeriod)
l_supertrend := barstate.isfirst ? na : l_supertrend
l_upTrend =    plot(l_direction < 0 ? l_supertrend : na, "Up Trend",   color = color.green, style = plot.style_linebr)
l_downTrend =  plot(l_direction < 0 ? na : l_supertrend, "Down Trend", color = color.red,   style = plot.style_linebr)
l_bodyMiddle = plot(barstate.isfirst ? na : (open + close) / 2, "Body Middle", display = display.none)

fill(l_bodyMiddle, l_upTrend,   title = "Uptrend background",   color = color.new(color.green, 90), fillgaps = false)
fill(l_bodyMiddle, l_downTrend, title = "Downtrend background", color = color.new(color.red,   90), fillgaps = false)

[h_supertrend, h_direction] = request.security(syminfo.tickerid, higherTimeFrame, ta.supertrend(factor, atrPeriod))
h_supertrend := barstate.isfirst ? na : h_supertrend
h_upTrend =    plot(h_direction < 0 ? h_supertrend : na, "Up Trend",   color = color.green, style = plot.style_linebr)
h_downTrend =  plot(h_direction < 0 ? na : h_supertrend, "Down Trend", color = color.red,   style = plot.style_linebr)
h_bodyMiddle = plot(barstate.isfirst ? na : (open + close) / 2, "Body Middle", display = display.none)

fill(h_bodyMiddle, h_upTrend,   title = "Uptrend background",   color = color.new(color.green, 90), fillgaps = false)
fill(h_bodyMiddle, h_downTrend, title = "Downtrend background", color = color.new(color.red,   90), fillgaps = false)

// Signal conditions
var int shortC = 0

// Reset all state at the start of each new trading day
if ta.change(time("D")) != 0
    shortC := 0

crossL     = ta.crossunder(close, l_supertrend)
crossH     = ta.crossunder(close, h_supertrend)

shortExit  = shortC != 0 and (close > l_supertrend or close > h_supertrend) and barstate.isconfirmed
shortEntry = shortC == 0 and ((crossL and close < h_supertrend) or (crossH and close < l_supertrend)) and barstate.isconfirmed

if shortExit
    shortC := 0
if shortEntry
    shortC := 1

// ===== ALERTS ===== //
alertcondition(shortEntry, "Short Entry Alert", "supertrend: SELL")
alertcondition(shortExit,  "Short Close Alert", "supertrend: CLOSE SHORT")

// Plot signals
plotshape(shortEntry, title="Short Entry", style=shape.arrowdown, location=location.abovebar, color=color.red,   text="Short")
plotshape(shortExit,  title="Short Exit",  style=shape.arrowup,   location=location.belowbar, color=color.green, text="Exit Short")
