//@version=6
indicator("9-21 EMA Crossover -india (Pivot Trail Stops)","921PivInd", overlay = true)

// Inputs
emaFastLength = input.int(9, "Fast EMA Length")
emaSlowLength = input.int(21, "Slow EMA Length")
use_atr_distance = input.bool(title="Use ATR for Distance Filter", defval=true)
distanceMultiplier = input.float(title="Distance Multiplier (ATR)", defval=0.5, step=0.1)
minBarsBetweenCrosses = input.int(5, "Min Bars Between Crossovers", minval=1)
enableReentries = input.bool(true, "Enable Reentries")
maxReentries = input.int(2, "Max Reentries", minval=0)
pivotBarsLeft = input.int(2, "Pivot Left Bars", minval=1)
pivotBarsRight = input.int(2, "Pivot Right Bars", minval=1)

var int crossBarIndex = 0
var float longStoploss = na
var float shortStoploss = na
var bool isLong = false
var bool isShort = false
var bool lastExitWasShort = false
var int  reentryCount = 0

// Calculate EMAs
emaFast = ta.ema(close, emaFastLength)
emaSlow = ta.ema(close, emaSlowLength)

// calculate Pivot 
pivotHigh  = ta.pivothigh(pivotBarsLeft, pivotBarsRight)
pivotLow = ta.pivotlow(pivotBarsLeft, pivotBarsRight)
if(not na(pivotHigh))
    shortStoploss := pivotHigh
if(not na(pivotLow))
    longStoploss := pivotLow
// Calculate ATR for entry distance 0
atr = ta.atr(14)

// Crossover Conditions
bullishCross = ta.crossover(emaFast, emaSlow)
bearishCross = ta.crossunder(emaFast, emaSlow)

//Long Exit Condition
longExit  = isLong and bearishCross and barstate.isconfirmed 
if(longExit)
    isLong := false
    lastExitWasShort := false
    reentryCount := 0

pivotCrossOver = ta.crossover(close, shortStoploss)
//Short Exit Condition 
shortExit = isShort and  (bullishCross or pivotCrossOver)  and barstate.isconfirmed
if(shortExit)
    isShort := false
    lastExitWasShort := true
    reentryCount := 0

// Calculate minDistance based on flag
minDistance = use_atr_distance ? (atr * distanceMultiplier) : na
// Calculate distance checks
longDistanceOk = not use_atr_distance ? true : (math.abs(close - emaFast) > minDistance) and minBarsBetweenCrosses < bar_index - crossBarIndex
shortDistanceOk = not use_atr_distance ? true : (math.abs(close - emaSlow) > minDistance) and minBarsBetweenCrosses < bar_index - crossBarIndex
//Long Entry Condition
longCondition = not isLong and not isShort and  bullishCross  and barstate.isconfirmed
if(longCondition)
    isLong := true
    lastExitWasShort := false
    reentryCount := 0
//Short Entry Condition
shortCondition = not isLong and not isShort  and  bearishCross  and shortDistanceOk and  barstate.isconfirmed
if(shortCondition)
    isShort := true
    reentryCount := 0


// short Reentry
lowestLow5 =  ta.lowest(low, 5)[1]
shortReentry = enableReentries and not isLong and not isShort and 
             lastExitWasShort and close < lowestLow5 and reentryCount < maxReentries
if shortReentry
    isShort := true
    reentryCount :=reentryCount + 1


if bullishCross or bearishCross
    crossBarIndex := bar_index
    lastExitWasShort := false

if bearishCross and not isShort
    lastExitWasShort := true
// Plotting
plot(emaFast, color=color.new(color.blue, 0), title="9 EMA")
plot(emaSlow, color=color.new(color.black, 0), title="21 EMA")


// Highlight Crossovers
plotshape(bullishCross, style=shape.xcross, location=location.belowbar, color=color.new(color.green, 0), size=size.tiny, title="Bullish Cross")
plotshape(bearishCross, style=shape.xcross, location=location.abovebar, color=color.new(color.red, 0), size=size.tiny, title="Bearish Cross")

plot(isShort ? shortStoploss : na, "Short Trail", color.new(color.red, 50), 2, plot.style_linebr)


// Plot position signals
plotshape(longCondition, title="Long Entry", style=shape.arrowup, location=location.abovebar, color=color.green, text="Long")
plotshape(longExit, title="Long Exit", style=shape.arrowdown, location=location.belowbar, color=color.red, text="Exit Long")
plotshape(shortCondition, title="Short Entry", style=shape.arrowdown, location=location.abovebar, color=color.green, text="Short")
plotshape(shortReentry, title="Short Entry", style=shape.arrowdown, location=location.abovebar, color=color.green, text="Re-Short")

plotshape(shortExit, title="Short Exit", style=shape.arrowup, location=location.belowbar, color=color.red, text="Exit Short")

// ===== ALERTS ===== //
alertcondition(longCondition,  "Long Entry Alert",  "9-21-cross: BUY")
alertcondition(shortCondition or shortReentry, "Short Entry Alert", "9-21-cross: SELL")
alertcondition(longExit,   "Long Exit Alert",   "9-21-cross: CLOSE LONG")
alertcondition(shortExit,  "Short Exit Alert",  "9-21-cross: CLOSE SHORT")